### ISSUE TITLE
Provide clear indication when service is down and all routes display "scheduled"

### ISSUE THREAD

**Issue by leecolleton** [OneBusAway/onebusaway#10]
When all routes display scheduled arrival or departure the interface should provide a clear indication that there is no live data.

**Comment by barbeau** [comment]
@leecolleton Thanks for your feedback!  I agree that there should be a clear indicator when service is down!  This is best managed by each agency that deploys OneBusAway, as they know what's happening in real-time, and would have more exact information about the expected duration of the outage and anything else that should be communicated to riders.  OneBusAway supports creating "Service Alerts", which allows the agency to communicate this information to riders - see https://github.com/OneBusAway/onebusaway-application-modules/wiki/Creating-Service-Alerts for more details.

I'm going to close this issue because Service Alerts are already supported.  Please pass this information on to your local OneBusAway agency if they aren't currently using this feature.  Please also feel free to have them reach out to me or anyone else via email or on the [onebusaway-users Google Group](https://groups.google.com/forum/#!forum/onebusaway-users) if they have questions about using this feature.  Thanks for using OneBusAway!
